%% CMTK wrapper
%% 1) Main functions to run registration and reformat
cmtk_intfunc
% function that handles cmtk tools
% it executes registration, warp and reformat functions from CMTK
% out = cmtk_intfunc(func2use, redo, iIm, oIm, ...
%   refIm, xform, oDir, refDir, iDir, aDir, xDir, iparams)

cmtk_paramgen
% generate default parameters used by CMTK internal function
%   'cmtk_intfunc'
% cmtkpars = cmtk_paramgen(iparams, verbose_)

%% 2) Read or write registration text files

cmtk_write_init_affine
% write initial_affine text file
% cmtk_write_init_affine(iparams, oDir)

cmtk_read_registration
% read text files generated by initial affine | registration(x)
% params = cmtk_read_registration(txtfname)

%% 3) Transform images or coordinates

cmtk_xform
% reformat xyz points (matrix of points or trees) from one reference to another reference coordinates
% [iObject, err_] = cmtk_xform(iObject, refi, refo, iparams)

cmtk_xform_im
% transform images from source to target coordinate system
% status_ = cmtk_xform_im(refi, refo, iFloat, oFloat, iparams)

%% 4) avegare - active deformation model

cmtk_avg_adm
% Generate an average-deformation average intensity image
% based on a set of input transforms and reference image using.
%   cmtk_avg_adm(refiter, files2run, refi, oImDir)

%% 5) Deformation-Based Morphometry

cmtk_dbm_parse_j_and_tval_and_tnull
% deformation-based morphometry, it loads jacobians from 'nrrd' files and
% saves them in a memmap '.mat' file, calculates two-sample t-statistic,
% and the null distribution of t-stat.
% cmtk_dbm_parse_j_and_tval_and_tnull(inputfiles, iparams)

cmtk_dbm_parse_j_and_tval
% Same as before without the null distribution of t-stat
% cmtk_dbm_raw_cmp_tval(inputfiles, iparams)

%% 6) ToDo

% write a demo
% Ideas:
% have exampe 1-5 nrrd files, and nsybIVA template
% make a demo using registration/
